#version: "2"
services: 
  mongo2:
    image: mongo:4.0.4
    container_name: mongo2
    restart: always
    volumes:
      - ./db/mongod.conf:/etc/mongod.conf
      #- ./logs:/var/log/mongod/
      - ./db:/var/lib/mongodb
      #- ./mongod.service:/lib/systemd/system/mongod.service
    ports:
      - "27017:27017"

  app2:
    container_name: app2
    restart: always
    build: ./web
    ports:
      - "80:3000"
    links:
      - mongo2
    environment: 
      - DB_HOST=mongodb://mongo2:27017/posts
    depends_on:
      - mongo2

